development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cmsimple_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: cmsimple_test
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

cucumber:
  <<: *test
