rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - mysql -e 'create database cmsimple_test;'
  - 'cp spec/rails_app/config/database.example.yml spec/dummy/rails_app/database.yml'
  - 'sh -e /etc/init.d/xvfb start'
env:
  - DISPLAY=':99.0' CUCUMBER_OPTS='-f progress'
script: bundle exec rake --trace
